Install: PSO*7.0*465
Patch Subject:  CMOP TRANSMISSION STOPPED DURING NIGHT/HL7 DOCUMENTATION
Description:

============
 This patch addresses the following issues:
   1. The CMOP transmission stopped due to an Undefined error
   2. ScriptPro issue with temporary address on label
 Associated CA SDM Tickets:
 ==========================
 1. I8485105FY16 - CMOP transmission stopped during the night (PSI)
 2. I9916149FY16 - ScriptPro issue with temporary address on label
 Associated NSR(s):
 ==================
 N/A
 Participating Test Sites:
 =========================
 Oklahoma City VAMC
 Maryland HCS
 CA SDM Overview:
 ================
 1. I8485105FY16 - CMOP transmission stopped during the night
 Patient Safety Issue:
 --------------------
 PSPO 2979
 Problem:
 --------
 The controlled substance prescription CMOP (Consolidated Mail Outpatient
 Pharmacy) transmission went through all right but the process errored out
 on the non-controlled substance prescription with the following message:
 Subj: CMOP Error WACO 93447 [#24160246] 04/21/16@03:17 6 lines
 From: Users Name - IT SPECIALIST (VISTA SUPPORT) In 'IN' basket.
 Page 1 *New*
 --------------------------------------------------------------------------
 NON-CS CMOP Transmission encountered the following error. Please
 investigate
 Division: WACO
 Type/Batch NON-CS / 93447
 Error: <UNDEFINED>DG1+15^PSOHLSN2 *PSOARRY(1)
 The prescriptions have been reset and other divisions' transmissions are
 continuing.
 Resolution:
 -----------
 Modify routine PSOHLSN2 to Quit at the beginning of tag DG1 so the ICD
 checks are not performed.  Also add a comment above this Quit to note
 that if these checks are needed in the future, the code will need to be
 re-evaluated for any necessary changes.
 2. I9916149FY16 - ScriptPro issue with temporary address on label
 Problem:
 --------
 The Technical Manual/Security Guide is not up to date with the way
 the patient's addresses (Confidential and Temporary) are sent in the
 HL7 record.
 Resolution:
 -----------
 Update the Technical Manual/Security Guide to correctly show where the
 patient's Confidential and Temporary addresses will be located in the
 HL7 record.
 DOCUMENTATION RETRIEVAL INSTRUCTIONS:
 =====================================
 Updated documentation that goes with Issue 2 above in this patch is
 available.
 The preferred method is to retrieve files from download.vista.domain.ext.
 This transmits the files from the first available server. Sites may
 also elect to retrieve files directly from a specific server.
 Sites may retrieve the documentation directly using Secure File Transfer
 Protocol (SFTP) from the ANONYMOUS.SOFTWARE directory at the following OI
 Field Offices:
 Albany:                 domain.ext
 Hines:                  domain.ext
 Salt Lake City:         domain.ext
 Documentation can also be found on the VA Software Documentation Library
 at: http://www.domain.ext/vdl/
 File Name           Description                        Format
 =========           ===========                        ======
 pso_7_tm.pdf        TECHNICAL MANUAL/SECURITY GUIDE    Binary
 pso_7_tm_r0417.pdf  TECHNICAL MANUAL/SECURITY GUIDE    Binary

Use default answers for KIDS load/install questions.

Patch-Files: http://code.osehra.org/VistA.git/tree/master/Packages/Outpatient+Pharmacy/Patches/PSO_7.0_465